# builtin DataStructures

In [ ]:
# datatypes
t_i: int
t_f: float
t_c: complex = 1 + 2j
t_s: str
t_b: bool
t_y: bytes
# bytearray

In [7]:
# datastructures
ds_l: list = [1, 2, 3]
ds_t: tuple = (1, 2, 3)
ds_d: dict = {1: "hello", 2: "world"}
ds_s: set = {1, 2, 3}
ds_f: frozenset = frozenset({1, 2, 3})

In [ ]:
# collections
from collections import deque  # stack, queue, linked list, graph, ...

In [ ]:
# iterables (iter, next)

In [ ]:
# generators (yield, next)

In [ ]:
from types import NoneType
from typing import Any
import datetime

## Pydantic

In [ ]:
from pydantic import BaseModel

## Dataclass Decorator

In [ ]:
from dataclasses import dataclass

# DataScience Libraries

### Tutorials
https://www.w3schools.com/python/numpy/default.asp

https://www.datacamp.com/tutorial/python-numpy-tutorial

https://www.geeksforgeeks.org/python/numpy-tutorial/

https://www.programiz.com/python-programming/numpy

### Cheat Sheets
https://www.datacamp.com/cheat-sheet

https://github.com/FavioVazquez/ds-cheatsheets

https://medium.com/@anushka.datascoop/101-data-science-cheat-sheets-ml-dl-scraping-python-r-sql-maths-statistics-ef30b4d786eb

In [8]:
import numpy as np
import pandas as pd
import scipy as sp
import sklearn as sk

import matplotlib.pyplot as plt
import seaborn as sns
import bokeh
import streamlit as st

from numba import jit, njit

### NumPy
https://numpy.org/

https://numpy.org/doc/stable/

https://github.com/numpy/numpy


In [9]:
import numpy as np

# np.info(np.ndarray.dtype)
a = np.array([(0,0,0), (0,0,0)], dtype=np.float64)
print("a: ndim ==", a.ndim, ", shape ==", a.shape, "\n", a)
b = np.arange(-10, 10, 2)
print("\nb:\n", b)
c = np.random.random((2, 3, 4))
print("\nc: ndim ==", c.ndim, ", shape ==", c.shape, "\n", c)
d = np.empty((2, 3))
print("\nd:\n", d)

a: ndim == 2 , shape == (2, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]]

b:
 [-10  -8  -6  -4  -2   0   2   4   6   8]

c: ndim == 3 , shape == (2, 3, 4) 
 [[[0.52770652 0.48141119 0.19037356 0.34899464]
  [0.81194531 0.80745117 0.00536724 0.75874139]
  [0.34982088 0.65330272 0.42083324 0.60575772]]

 [[0.32007537 0.58109708 0.9136067  0.15942395]
  [0.57939523 0.3853121  0.34696393 0.78623386]
  [0.13846176 0.31408333 0.1005478  0.3204584 ]]]

d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# Slicing
print(b[1:6])
print(b[1:2])

[-8 -6 -4 -2  0]
[-8]


### Pandas
https://pandas.pydata.org/

https://pandas.pydata.org/docs/

https://github.com/pandas-dev/pandas


In [13]:
import pandas as pd

df = pd.DataFrame(np.random.randn(10, 5))
print(df)

          0         1         2         3         4
0  1.410581 -1.037159 -1.853718  0.715868 -0.405762
1 -1.665053 -0.481656  0.304795  0.250721 -1.322102
2 -0.108459  1.887141  0.848961  1.535551 -0.234678
3 -1.726009 -1.233100  1.151782 -1.342627 -1.588329
4  0.379697 -0.711046 -0.135794  0.131507  0.611900
5 -2.450640 -0.072400  0.972099  0.474693  0.155217
6  0.420618  2.346637  0.453986  0.677277  0.570319
7 -0.965587  0.645738  0.463777 -0.114215  0.019365
8  0.199079 -0.810680 -0.732313 -0.092759 -0.837703
9 -1.853709  0.364416 -0.088943  1.586267 -0.147744


### Matplotlib
https://matplotlib.org/

https://github.com/matplotlib/matplotlib

### Seaborn
https://seaborn.pydata.org/

### Bokeh
https://bokeh.org/

https://github.com/bokeh/bokeh

### Plotly
https://plotly.com/python/

https://github.com/plotly/plotly.py


### StreamLit
https://streamlit.io/

https://docs.streamlit.io/

https://blog.streamlit.io/

https://github.com/streamlit/streamlit

```bash
streamlit hello
```
runs a Web App from the Terminal; access in Browser http://localhost:8501/

#### Streamlit in Jupyter
https://discuss.streamlit.io/t/new-library-streamlit-jupyter-a-new-way-to-develop-streamlit-apps-in-jupyter-notebooks/35679

https://docs.kanaries.net/topics/Streamlit/streamlit-jupyterlab


In [1]:
import streamlit as st
# must be run from Terminal

st.write("""
# Welcome to *Streamlit*
Hello, World!
""")

2025-09-04 11:02:35.114 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-04 11:02:35.725 
  command:

    streamlit run L:\WORKSPACES\PYTHON_WS\python_template\.venv\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-09-04 11:02:35.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-04 11:02:35.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


### SciPy
https://scipy.org/

https://docs.scipy.org/doc/scipy/

https://github.com/scipy/scipy


In [12]:
import scipy as sp

print(sp.constants.pi)
print(dir(sp.constants))

3.141592653589793
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_

### Numba
https://numba.pydata.org/

https://github.com/numba/numba


# Machine Learning

### Scikit-Learn
https://scikit-learn.org/stable/

https://github.com/scikit-learn/scikit-learn

### Scikit-Image
https://github.com/scikit-image/scikit-image


In [8]:
import sklearn as sk
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[0])
print(y[0])  # classified class

[5.1 3.5 1.4 0.2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
