## DeepLearning

### TensorFlow
https://www.tensorflow.org/

https://github.com/tensorflow/tensorflow


### Keras
https://keras.io/

https://github.com/keras-team/keras


### PyTorch
https://pytorch.org/get-started/locally/

https://pytorch.org/get-started/previous-versions/

https://github.com/pytorch/pytorch

https://github.com/facebookresearch


#### Nvidia CUDA-Toolkit
https://developer.nvidia.com/cuda-toolkit-archive

https://developer.nvidia.com/cuda-12-6-3-download-archive (for GTX 1060 6GB GPU)

```bash
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
```

---

https://docs.nvidia.com/cuda/

https://github.com/NVIDIA


In [12]:
import torch
print("CUDA available: ", torch.cuda.is_available())
print("GPU name:       ", torch.cuda.get_device_name(0))  # sm_61
print("Torch Version:  ", torch.__version__)
print("Torch CUDA:     ", torch.version.cuda)
print("Torch CUDNN:    ", torch.backends.cudnn.version())
print("Torch Arch List:", torch.cuda.get_arch_list())

CUDA available:  True
GPU name:        NVIDIA GeForce GTX 1060 6GB
Torch Version:   2.8.0+cu126
Torch CUDA:      12.6
Torch CUDNN:     91002
Torch Arch List: ['sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90']


In [13]:
import torch

# initializing tensors
device = "cuda" if torch.cuda.is_available() else "cpu"
t1 = torch.tensor([[1,2,3], [4,5,6]], device=device, requires_grad=True, dtype=torch.float32)
t2 = torch.zeros(3, 3, device=device, dtype=torch.float32)
# t2 = torch.ones(3, 3, device=device, dtype=torch.float32)
# t2 = torch.rand(3, 3, device=device, dtype=torch.float32)
# t2 = torch.randn(3, 3, device=device, dtype=torch.float32)
# t2 = torch.eye(3, device=device, dtype=torch.float32
# t2 = torch.arange(9, device=device, dtype=torch.float32)
# t2 = torch.linspace(0, 10, 11, device=device, dtype=torch.float32)

# tensor operations
t3 = torch.matmul(t1, t2)
print(t3)
t3.backward(torch.ones_like(t3))
print(t1.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', grad_fn=<MmBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [14]:
import numpy as np

a1 = np.zeros((3, 3))      # numpy array
t1 = torch.from_numpy(a1)  # torch tensor
a2 = t1.numpy()            # numpy array

print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
