# builtin DataStructures

In [ ]:
# datatypes
t_i: int
t_f: float
t_c: complex = 1 + 2j
t_s: str
t_b: bool
t_y: bytes
# bytearray

In [7]:
# datastructures
ds_l: list = [1, 2, 3]
ds_t: tuple = (1, 2, 3)
ds_d: dict = {1: "hello", 2: "world"}
ds_s: set = {1, 2, 3}
ds_f: frozenset = frozenset({1, 2, 3})

In [ ]:
# collections
from collections import deque  # stack, queue, linked list, graph, ...

In [ ]:
# iterables (iter, next)

In [ ]:
# generators (yield, next)

In [ ]:
from types import NoneType
from typing import Any
import datetime

## Pydantic

In [ ]:
from pydantic import BaseModel

## Dataclass Decorator

In [ ]:
from dataclasses import dataclass

# DataScience Libraries

In [8]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import streamlit as st
from numba import jit, njit

### NumPy

In [9]:
# np.info(np.ndarray.dtype)
a = np.array([(0,0,0), (0,0,0)], dtype=np.float64)
print("a: ndim ==", a.ndim, ", shape ==", a.shape, "\n", a)
b = np.arange(-10, 10, 2)
print("\nb:\n", b)
c = np.random.random((2, 3, 4))
print("\nc: ndim ==", c.ndim, ", shape ==", c.shape, "\n", c)
d = np.empty((2, 3))
print("\nd:\n", d)

a: ndim == 2 , shape == (2, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]]

b:
 [-10  -8  -6  -4  -2   0   2   4   6   8]

c: ndim == 3 , shape == (2, 3, 4) 
 [[[0.52770652 0.48141119 0.19037356 0.34899464]
  [0.81194531 0.80745117 0.00536724 0.75874139]
  [0.34982088 0.65330272 0.42083324 0.60575772]]

 [[0.32007537 0.58109708 0.9136067  0.15942395]
  [0.57939523 0.3853121  0.34696393 0.78623386]
  [0.13846176 0.31408333 0.1005478  0.3204584 ]]]

d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# Slicing
print(b[1:6])
print(b[1:2])

[-8 -6 -4 -2  0]
[-8]


### Pandas

In [13]:
#from datasets import load_dataset
df = pd.DataFrame(np.random.randn(10, 5))
print(df)

          0         1         2         3         4
0  1.410581 -1.037159 -1.853718  0.715868 -0.405762
1 -1.665053 -0.481656  0.304795  0.250721 -1.322102
2 -0.108459  1.887141  0.848961  1.535551 -0.234678
3 -1.726009 -1.233100  1.151782 -1.342627 -1.588329
4  0.379697 -0.711046 -0.135794  0.131507  0.611900
5 -2.450640 -0.072400  0.972099  0.474693  0.155217
6  0.420618  2.346637  0.453986  0.677277  0.570319
7 -0.965587  0.645738  0.463777 -0.114215  0.019365
8  0.199079 -0.810680 -0.732313 -0.092759 -0.837703
9 -1.853709  0.364416 -0.088943  1.586267 -0.147744


### SciPy

In [12]:
print(sp.constants.pi)
print(dir(sp.constants))

3.141592653589793
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_

# Machine Learning

In [ ]:
import sklearn as sk

# PyTorch + CUDA Toolkit
https://pytorch.org/get-started/locally/

https://pytorch.org/get-started/previous-versions/

In [6]:
import torch
print("CUDA available: ", torch.cuda.is_available())
print("GPU name:       ", torch.cuda.get_device_name(0))  # sm_61
print("Torch Version:  ", torch.__version__)
print("Torch CUDA:     ", torch.version.cuda)
print("Torch CUDNN:    ", torch.backends.cudnn.version())
print("Torch Arch List:", torch.cuda.get_arch_list())

CUDA available:  True
GPU name:        NVIDIA GeForce GTX 1060 6GB
Torch Version:   2.8.0+cu129
Torch CUDA:      12.9
Torch CUDNN:     91002
Torch Arch List: ['sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90', 'sm_100', 'sm_120']


Error: GPU (sm_61) not compatible with Torch (>= sm_70).

# Transformers

In [ ]:
from transformers import pipeline

# Fine-Tuning LLMs
https://youtu.be/pTaSDVz0gok

In [15]:
from unsloth import FastLanguageModel
from datasets import Dataset
from trl import SFTTrainer
from transformers import TrainingArguments
#from google.colab import files

#import torch
import json
import os

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.


L:\WORKSPACES\PYTHON_WS\python_template\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W0831 02:17:19.472000 13680 .venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.


ValueError: Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

ValueError: Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

# Huggingface_hub
https://github.com/huggingface/huggingface_hub

# Ollama
https://github.com/ollama/ollama-python


# MCP
https://mcp.so/

https://modelcontextprotocol.io/docs/getting-started/intro

https://github.com/modelcontextprotocol/servers

https://github.com/modelcontextprotocol/python-sdk

# LangChain
https://python.langchain.com/docs/introduction/

In [22]:
from langchain.chat_models import init_chat_model
import os
import dotenv
dotenv.load_dotenv()
#api_key = os.getenv("GOOGLE_API_KEY")

model = init_chat_model("gemini-2.5-flash", model_provider="google_genai")
model.invoke("Why is the Sky blue?")

AIMessage(content='The sky is blue because of a phenomenon called **Rayleigh scattering**. Here\'s a breakdown of why:\n\n1.  **Sunlight is White Light:** The light from the sun appears white to us, but it\'s actually made up of all the colors of the rainbow (red, orange, yellow, green, blue, indigo, violet). Each of these colors has a different **wavelength**. Blue and violet light have shorter, smaller wavelengths, while red and orange light have longer, larger wavelengths.\n\n2.  **Earth\'s Atmosphere:** Our planet is surrounded by an atmosphere composed of tiny gas molecules, primarily nitrogen (about 78%) and oxygen (about 21%). These molecules are much smaller than the wavelengths of visible light.\n\n3.  **The Scattering Effect:** When sunlight enters the atmosphere, it bumps into these tiny gas molecules. This causes the light to scatter in all directions.\n\n4.  **Why Blue is Scattered More:** Rayleigh scattering states that light with shorter wavelengths (like blue and violet

# Google Gemini API

In [14]:
from google import genai
from dotenv import load_dotenv
load_dotenv()
#client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
# The client gets the API key from the environment variable GEMINI_API_KEY
client = genai.Client()

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Explain how AI works in a few words",
)

print(response.text)

**Machines learn from data to find patterns and make intelligent decisions.**
